version: "3.8"

networks:
  default:

services:
  db:
    image: postgres:14.5
    container_name: periodical_subscription_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: periodicalSubscription
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./src/main/resources/migrations:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data